spring:
  datasource:    url: jdbc:h2:tcp://localhost/~/event-api
    username: admin
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
